### ISSUE TITLE
Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".

### ISSUE THREAD

**Issue by karlwilbur** [jeffleeismyhero/Zocial-Rails#3]
I believe that this is an issue with the version of css-social-buttons used by zocial-rails.

```
autoprefixer: /home/karl/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/zocial-rails-1.0.2/vendor/assets/stylesheets/zocial.css:116:2: Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".
autoprefixer: /home/karl/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/zocial-rails-1.0.2/vendor/assets/stylesheets/zocial.css:200:2: Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".
autoprefixer: /home/karl/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/zocial-rails-1.0.2/vendor/assets/stylesheets/zocial.css:230:2: Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".
```
ruby (2.2.2)
rails (4.2.3)
autoprefixer-rails (5.2.1.3)
zocial-rails (1.0.2)

**Comment by jeffleeismyhero** [comment]
Hi @karlwilbur. I've updated the Zocial assets to use the most recent versions available from the project. Please let me know if you have any issues.

**Comment by karlwilbur** [comment]
Awesome!! Thank you, sir!

**Comment by karlwilbur** [comment]
This is still happening even with the most recent commits. Definitely a Zocial issue. I opened an issue there:
https://github.com/samcollins/css-social-buttons/issues/90

**Comment by jeffleeismyhero** [comment]
Hi Karl,

I see that your PR was merged into css-social-buttons. I've pulled those changes in here as well. Please let me know if v1.0.5 works for you, and I'll close this issue.

Thanks,
Jeff

**Comment by karlwilbur** [comment]
Will do. I was going to do that and submit a PR but you beat me to it. Thanks!

Looks like you didn't bump the version number though: 
https://github.com/jeffleeismyhero/Zocial-Rails/blob/v1.0.5/lib/zocial-rails/version.rb

**Comment by jeffleeismyhero** [comment]
Bah. I've bumped it to v1.0.6.

**Comment by karlwilbur** [comment]
Yep, that did it! No more warnings. Thanks!

``` diff
# Gemfile.lock [diff]
+  GIT
+  remote: git://github.com/jeffleeismyhero/Zocial-Rails.git
+  revision: b68e064490a5d772fbc831b501b048eefedcac44
+  specs:
+    zocial-rails (1.0.6)
+      railties (>= 3.1)
```

**Comment by jeffleeismyhero** [comment]
I've also pushed version 1.0.6 to Rubygems.org.
